reboot:
  target:
    device:
      integration: miner_hvac

restart_backend:
  target:
    device:
      integration: miner_hvac

curtail_wakeup:
  target:
    device:
      integration: miner_hvac

curtail_sleep:
  target:
    device:
      integration: miner_hvac
